plugins:
  gitpod-io/gitbot:
    plugins:
      - config-updater
      - help
      - hold
      - release-note
      - size
      - wip
  gitpod-io/gitpod:
    plugins:
      - help
      - hold
      - release-note
      - size
      - wip
  gitpod-io/gitpod-test-repo:
    plugins:
      - help
      - hold
      - release-note
      - size
      - wip
  gitpod-io/ops:
    plugins:
      - wip

config_updater:
  maps:
    config/config.yaml:
      name: config
    config/plugins.yaml:
      name: plugins

size:
  s: 10
  m: 30
  l: 90
  xl: 270
  xxl: 520
