plugins:
  gitpod-io/gitbot:
    plugins:
      - config-updater
      - help
      - hold
      - label
      - release-note
      - size
      - wip
  gitpod-io/gitpod:
    plugins:
      - help
      - hold
      - label
      - release-note
      - size
      - wip
  gitpod-io/gitpod-test-repo:
    plugins:
      - help
      - hold
      - release-note
      - size
      - wip
  gitpod-io/ops:
    plugins:
      - wip

external_plugins:
  "gitpod-io/gitpod":
    - name: customlabels
      endpoint: http://customlabels.prow.svc.cluster.local:8787
      events:
        - issues
        - issue_comment
        - pull_request
  "gitpod-io/gitpod-test-repo":
    - name: customlabels
      endpoint: http://customlabels.prow.svc.cluster.local:8787
      events:
        - issues
        - issue_comment
        - pull_request
    - name: willkommen
      endpoint: http://willkommen.prow.svc.cluster.local:8787
      events:
        - pull_request
        - issue_comment

config_updater:
  maps:
    config/config.yaml:
      name: config
    config/plugins.yaml:
      name: plugins
    config/customlabels.yaml:
      name: customlabels

size:
  s: 10
  m: 30
  l: 90
  xl: 270
  xxl: 520
