orgsRepos:
  "gitpod-io":
    fromRepos:
    - gitpod-io/gitpod
    projects:
      "Engineering Groundwork":
        columns:
          - id: 14782120
            org: "gitpod-io"
            labels:
              - "groundwork: scheduled"
            state: "open"
          - id: 14782132
            org: "gitpod-io"
            labels:
              - "groundwork: in progress"
            state: "open"
          - id: 14782135
            org: "gitpod-io"
            labels:
              - "groundwork: in review"
            state: "open"
          - id: 14782150
            org: "gitpod-io"
            labels:
              - "groundwork: awaiting deployment"
            state: "closed"
          - id: 14782155
            org: "gitpod-io"
            labels:
              - "groundwork: deployed"
            state: "closed"
          # If none of the above matches, use Inbox for open issues...
          - id: 14795239
            org: "gitpod-io"
            state: "open"
          # ...and Deployed for close ones
          - id: 14782155
            org: "gitpod-io"
            state: "closed"
  "gitpod-io/gitpod-test-repo":
    fromRepos: 
    - gitpod-io/gitpod-test-repo
    projects:
      "Groundwork Test":
        columns:
          - id: 15074318
            org: "gitpod-io"
            labels:
              - "groundwork: scheduled"
            state: "open"
          - id: 15074320
            org: "gitpod-io"
            labels:
              - "groundwork: in progress"
            state: "open"
          - id: 15074324
            org: "gitpod-io"
            labels:
              - "groundwork: in review"
            state: "open"
          - id: 15074325
            org: "gitpod-io"
            labels:
              - "groundwork: awaiting deployment"
            state: "closed"
